### PR TITLE
Arm state controller merge

### PR DESCRIPTION
**Pull request by marcoesposito1988**
Basically a rebase of #41 on top of the Merge

### CODE REVIEW

**Comment by carlosjoserg** [comment]
Oh, I hadn't see the last message in #41, the vote for merging.

But the building of this one is failing too, it does not find the kdl_conversions package

Once this is merge is merge I'll close #41

**Comment by marcoesposito1988** [comment]
Yes, probably we have to add it to the packages installed through apt in the Travis script.

I'll do it ASAP

**Comment by carlosjoserg** [comment]
Ok, please, do the travis script update in a separate PR

**Comment by carlosjoserg** [comment]
I also found some discrepancies in the URDF related to the dynamic properties of links... I will PR the changes so you all can see what I'm talking about and why I believe the estimated values were not that accurate

I already added the kdl conversions to travis btw

**Comment by carlosjoserg** [comment]
Closing in favor of #74

**Comment by marcoesposito1988** [comment]
Cool! Nice to see you're back :) I will try the whole thing out as soon as possible.. probably in around 10 days. After that I may be more active myself again.

**Comment by carlosjoserg** [comment]
Great!

**Pull request closed without merging**
