### PR TITLE
Updating some deprecated commands for ROS Kinetic

### PR DESCRIPTION
**Pull request by hamalMarino**
Few changes to avoid various warnings when loading the model in ROS Kinetic.
All changes are compatible with ROS Indigo.

### CODE REVIEW

**Comment by hamalMarino** [comment]
Following what was said in #72, I also updated the functions `canSwitch` (now `prepareSwitch`) and `doSwitch`, but being willing not to break compatibility with `Indigo` (yet) I decided to check the ROS version from code instead at preproccesing.
@miguelprada and @carlosjoserg, any thoughts on this?

**Comment by carlosjoserg** [comment]
That's a cool solution to still keep a single `master` branch... in fact, I didn't know ROS had a a numbered version but ROS1 and ROS2 :joy:

**Comment by hamalMarino** [comment]
At least for now, with many (at least here!) still using `Indigo`...

**Comment by marcoesposito1988** [comment]
Tried it out under Kinetic, looks good!

However, I tried to merge this with #82 and that did not work: I always get the infamous "FRI interpolation error" when starting the impedance controller. I guess we can merge this branch, and then solve that issue later.

**Comment by manuelbonilla** [comment]
tested and working both real and simulated robot.

**Pull request merged**
