### PR TITLE
Fixing toque mode control

### PR DESCRIPTION
**Pull request by manuelbonilla**

### CODE REVIEW

**Comment by carlosjoserg** [comment]
Lot of commits, I will be commenting on them.

For now, don't pay attention to travis result, I'm trying to solve that. It is due to recent updates in travis in the python set up.

**Comment by carlosjoserg** [comment]
I wouldn't want to merge with so many confusing back&forth changes in files, and wrong commit logs, would you consider to rewrite the history with more clear changes?

Please, consider smaller increments (I'd suggest to do documentation changes using the web interface, it is easier for previewing, and additionally, won't interface by nature with code changes) and more descriptive commit logs.

**Comment by manuelbonilla** [comment]
ok, I'll do it again

**Comment by carlosjoserg** [comment]
:+1:   
We need effort_controllers

**Comment by manuelbonilla** [comment]
please cancel this pull reques so I can delete the branch

**Pull request closed without merging**
