### PR TITLE
Primitive PID tuning (MoveIt!) and FRI port number armonization

### PR DESCRIPTION
**Pull request by marcoesposito1988**
Hi guys,

I managed to move the robot with MoveIt!, even for quite large movements and with a decent behavior. I guess it would be a nice starting point for more experienced people.

Btw, the port number in the KRL script in the repo is 49939, so I would suggest to use it as a default everywhere.

### CODE REVIEW

**Comment by manuelbonilla** [comment]
Hi @marcoesposito1988 

Good work. Did you try using the PID controller with a fixed (and far from actual position) reference point? I think you are having a good performance for trajectories because moveit interpolate and thus you have always small errors. 
In the case you have a big errors the gains in the yalm file can be dangerous since they are big.
@carlosjoserg I think we can add this as a warning in the README.

Tanks for contributing @marcoesposito1988 

best

**Comment by marcoesposito1988** [comment]
Hi Manuel,

thanks! I played a bit more with it, and the high gains were indeed causing obscillations. This values should be an improvement.

I will continue working on it.

**Comment by carlosjoserg** [comment]
@marcoesposito1988
The mess you saw with the port number is because we have 2 arms with different port numbers, but thanks for the standardization, it is beneficial to understand the package.

I see you mdified the `joint_limits.yaml` file. You should know that these values are automatically generated from the URDF everytime the `roslaunch lwr_moveit setup_assistant.launch` is used (unless you avoid to overwrite that file explicitly). The parameter in the URDF model you should tweak to get the desired limit values is called `<xacro:property name="velocity_scale" value="3"/>`. I would recommend to use that, if you don't want this values to be overwritten accidentally with the MoveIt! setup.

@manuelbonilla 
The warning regarding the PID tunning is more or less there in the Overview section, check it whether it is enough or not.

The merge goes anyway, thanks again.

**Comment by marcoesposito1988** [comment]
Hi @carlosjoserg , 

I didn't know that, thanks! I'll do that next. Thanks for merging!

**Pull request merged**
