### PR TITLE
Fixing compilation issues

### LINKED ISSUE #32: Compilation error
I am getting the following error when running `catkin_make`:

```
kuka-lwr/lwr_controllers/src/joint_impedance_controller.cpp:94:101: error:
no ‘void lwr_controllers::JointImpedanceController::commandConfiguration(const ConstPtr&)’
member function declared in class ‘lwr_controllers::JointImpedanceController’
void JointImpedanceController::commandConfiguration(const std_msgs::Float64MultiArray::ConstPtr &msg){
```

@marcoesposito1988 you renamed `JointImpedanceController::command` to `JointImpedanceController::commandConfiguration` in https://github.com/CentroEPiaggio/kuka-lwr/commit/7319f24d487e67862acc40a905540018092f01c6 without changing the header file

*Edit*: Actually `JointImpedanceController::command` is mentioned in other places also. @marcoesposito1988 why did you change it to commandConfiguration in `lwr_controllers/src/joint_impedance_controller.cpp`?

### PR DESCRIPTION
**Pull request by nrontsis**
Fixes #32

### CODE REVIEW

**Comment by carlosjoserg** [comment]
And thanks for the PR. However, it has several other commits, could you PR only with c64cdb22264d692f62c8f0a863bc551c6b577b28? If it's too much trouble, let me know.

**Comment by nrontsis** [comment]
Sorry about that, I am newcomer to git.
I am closing and creating a new PR with only https://github.com/CentroEPiaggio/kuka-lwr/commit/c64cdb22264d692f62c8f0a863bc551c6b577b28.

Could you however explain me if there would be any difference if you did `git merge --squash` on this pull request?

**Comment by carlosjoserg** [comment]
Just an IKEA solution: transfer the work to the customer ; )

The main reason is that a rule of thumb for squashing is that you shouldn't do it in the remote/common repo, but in your local, in this case, your fork. If for any reason, anyone clone after I merge the PR in the remote, and start working and branch from any of the commits that I'll squash later, there might be conflicts. This is a very small project with a small community, and I could probably do the squash&push in less than 10 min if the power supply doesn't die, so this problem is not likely to occur. But it is safer anyway.

**Comment by nrontsis** [comment]
Hahaha :smile:

I see your point, thank you for the explanation.

**Pull request closed without merging**
